location               = "westeurope"
resource_group_name    = "order-notification-rg"
servicebus_namespace_name = "orderbusnamespace"
servicebus_topic_name  = "ordercreatedtopic"
aks_cluster_name       = "order-cluster"
